from fastapi import FastAPI, HTTPException, Request
from pydantic import BaseModel
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import TranscriptsDisabled, NoTranscriptFound
from google import genai
from google.genai import types
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request as GoogleAuthRequest
from googleapiclient.discovery import build
from dotenv import load_dotenv
import os, re, base64, json

load_dotenv()

app = FastAPI()
gemini_client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

def get_gmail_service():
    creds = Credentials(
        token=None,
        refresh_token=os.getenv("GMAIL_REFRESH_TOKEN"),
        token_uri="https://oauth2.googleapis.com/token",
        client_id=os.getenv("GMAIL_CLIENT_ID"),
        client_secret=os.getenv("GMAIL_CLIENT_SECRET"),
        scopes=["https://www.googleapis.com/auth/gmail.modify"]
    )
    creds.refresh(GoogleAuthRequest())
    return build("gmail", "v1", credentials=creds)

class ProcessRequest(BaseModel):
    video_url: str
    sender_email: str | None = None

class ProcessResponse(BaseModel):
    video_id: str
    video_url: str
    transcript_preview: str | None
    notes: str
    cached: bool = False

def extract_video_id(url: str) -> str:
    match = re.search(r"(?:v=|youtu\.be/)([a-zA-Z0-9_-]{11})", url)
    if not match:
        raise ValueError(f"Could not extract video ID from: {url}")
    return match.group(1)

def extract_youtube_url(text: str) -> str | None:
    match = re.search(
        r"https?://(?:www\.)?(?:youtube\.com/watch\?v=|youtu\.be/)([a-zA-Z0-9_-]{11})[^\s]*",
        text
    )
    return match.group(0) if match else None

def get_transcript(video_id: str) -> str | None:
    try:
        ytt_api = YouTubeTranscriptApi()
        fetched = ytt_api.fetch(video_id)
        return " ".join(snippet.text for snippet in fetched)
    except (TranscriptsDisabled, NoTranscriptFound):
        return None

def generate_study_material(video_url: str) -> str:
    prompt = """You are a study assistant. Based on this video, produce:
1. STRUCTURED NOTES — organized under topic headings
2. SUMMARY — 3-5 sentences
3. QUIZ — 5 questions with an answer key
4. FLASHCARDS — 5 question/answer pairs"""

    response = gemini_client.models.generate_content(
        model="gemini-2.5-flash",
        contents=types.Content(parts=[
            types.Part(text=prompt),
            types.Part(file_data=types.FileData(file_uri=video_url)),
        ])
    )
    return response.text

def send_reply(service, message_id: str, thread_id: str,
               to: str, subject: str, body: str, video_url: str):
    import markdown as md

    html_notes = md.markdown(body, extensions=["extra"])

    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 700px;
                 margin: auto; padding: 20px; color: #222;">

        <div style="background: #4F46E5; padding: 20px; border-radius: 10px;
                    margin-bottom: 24px;">
            <h1 style="color: white; margin: 0;">🎓 YouTube Learning Agent</h1>
            <p style="color: #c7d2fe; margin: 8px 0 0;">
                Your study materials are ready
            </p>
        </div>

        <div style="background: #F3F4F6; padding: 12px 20px;
                    border-radius: 8px; margin-bottom: 24px;">
            <strong>Video:</strong>
            <a href="{video_url}">{video_url}</a>
        </div>

        <div style="line-height: 1.7;">
            {html_notes}
        </div>

        <div style="margin-top: 32px; padding-top: 16px;
                    border-top: 1px solid #e5e7eb;
                    color: #6B7280; font-size: 13px;">
            Generated by YouTube Learning Agent • Built by Anna 
        </div>

    </body>
    </html>
    """

    import email.mime.multipart
    import email.mime.text

    msg = email.mime.multipart.MIMEMultipart("alternative")
    msg["To"] = to
    msg["Subject"] = f"Re: {subject}"
    msg["In-Reply-To"] = message_id
    msg["References"] = message_id
    msg.attach(email.mime.text.MIMEText(html, "html"))

    encoded = base64.urlsafe_b64encode(msg.as_bytes()).decode()
    service.users().messages().send(
        userId="me",
        body={"raw": encoded, "threadId": thread_id}
    ).execute()

@app.post("/webhook")
async def gmail_webhook(request: Request):
    body = await request.json()
    print("Webhook received")

    service = get_gmail_service()

    results = service.users().messages().list(
        userId="me",
        labelIds=["INBOX", "UNREAD"],
        maxResults=1
    ).execute()

    messages = results.get("messages", [])
    print("Unread messages found:", len(messages))

    if not messages:
        print("No unread messages, skipping")
        return {"status": "ok"}

    msg_id = messages[0]["id"]
    msg = service.users().messages().get(
        userId="me", id=msg_id, format="full"
    ).execute()

    headers = {h["name"]: h["value"] for h in msg["payload"]["headers"]}
    sender = headers.get("From", "")
    subject = headers.get("Subject", "YouTube Learning Agent")
    print("Processing email from:", sender, "subject:", subject)

    # get plain text body
    parts = msg["payload"].get("parts", [])
    email_body = ""
    for part in parts:
        if part["mimeType"] == "text/plain":
            email_body = base64.urlsafe_b64decode(
                part["body"]["data"]
            ).decode("utf-8")
            break

    # fallback for simple emails with no parts
    if not email_body:
        body_data = msg["payload"].get("body", {}).get("data", "")
        if body_data:
            email_body = base64.urlsafe_b64decode(body_data).decode("utf-8")

    print("Email body preview:", email_body[:200])
    video_url = extract_youtube_url(email_body)
    print("Video URL found:", video_url)

    if not video_url:
        print("No YouTube URL found, skipping")
        # mark as read so we don't reprocess it
        service.users().messages().modify(
            userId="me",
            id=msg_id,
            body={"removeLabelIds": ["UNREAD"]}
        ).execute()
        return {"status": "ok"}

    print("Generating study material...")
    notes = generate_study_material(video_url)
    reply_body = f"Here are your study materials for:\n{video_url}\n\n{notes}\n\n---\nYouTube Learning Agent"
    send_reply(service, msg_id, msg["threadId"], sender, subject, reply_body, video_url)
    print("Reply sent to:", sender)

    service.users().messages().modify(
        userId="me",
        id=msg_id,
        body={"removeLabelIds": ["UNREAD"]}
    ).execute()
    print("Marked as read")

    return {"status": "ok"}

@app.get("/health")
def health():
    return {"status": "ok"}

@app.post("/process", response_model=ProcessResponse)
def process_video(req: ProcessRequest):
    try:
        video_id = extract_video_id(req.video_url)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    transcript = get_transcript(video_id)

    try:
        notes = generate_study_material(req.video_url)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Gemini error: {str(e)}")

    return ProcessResponse(
        video_id=video_id,
        video_url=req.video_url,
        transcript_preview=transcript[:300] if transcript else None,
        notes=notes,
        cached=False
    )