[server]
enableXsrfProtection = false
enableCORS = false

[theme]
base = "light"
primaryColor = "#E8A700"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F9FC"
textColor = "#1C2733"
font = "sans serif"
